version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/TutorialProject
    expose:
      - "8000"
    ports:
      - "8000:8000"